# Generated by Django 5.0.6 on 2026-03-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='degree',
            field=models.CharField(blank=True, choices=[('bachelor', "Bachelor's"), ('master', "Master's"), ('phd', 'PhD / Research'), ('diploma', 'Diploma')], max_length=20),
        ),
    ]
