# Generated by Django 5.0.6 on 2026-03-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_degree'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('dept_user', 'Department User'), ('hod', 'Head of Department'), ('authority', 'Higher Authority'), ('admin', 'System Admin')], default='student', max_length=20),
        ),
    ]
