# Generated by Django 5.0.6 on 2026-03-23 15:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='complaint',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complaint',
            name='escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='escalation_level',
            field=models.IntegerField(choices=[(1, 'Level 1 — Department User'), (2, 'Level 2 — HOD'), (3, 'Level 3 — Higher Authority')], default=1),
        ),
        migrations.AddField(
            model_name='complaint',
            name='escalation_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='last_escalation_check',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('hostel', 'Hostel'), ('academics', 'Academics'), ('infrastructure', 'Infrastructure'), ('library', 'Library'), ('canteen', 'Canteen'), ('sports', 'Sports & Facilities'), ('harassment', 'Ragging'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
